export const apiEndpoints = {
  auth: {
    login: "/auth/login",
    signup: "/auth/signup",
    logout: "/auth/logout",
    logoutAll: "/auth/logout-all",
    refresh: "/auth/refresh",
    me: "/auth/me",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/auth/verify-email",
    resendVerification: "/auth/resend-verification",
    switchWorkspace: "/auth/switch-workspace",
    updateProfile: "/auth/me",
    requestEmailChange: "/auth/email-change/request",
    verifyEmailChange: "/auth/email-change/verify",
  },
  organizations: {
    list: "/organizations",
    details: (organizationId: string) => `/organizations/${organizationId}`,
    members: (organizationId: string) => `/organizations/${organizationId}/members`,
    invite: (organizationId: string) => `/organizations/${organizationId}/members/invite`,
    updateMember: (organizationId: string, memberId: string) => `/organizations/${organizationId}/members/${memberId}`,
    removeMember: (organizationId: string, memberId: string) => `/organizations/${organizationId}/members/${memberId}`,
    transferOwnership: (organizationId: string) => `/organizations/${organizationId}/transfer-ownership`,
    join: "/organizations/join",
    joinRequests: (organizationId: string) => `/organizations/${organizationId}/join-requests`,
    approveJoinRequest: (organizationId: string, requestId: string) => `/organizations/${organizationId}/join-requests/${requestId}/approve`,
    rejectJoinRequest: (organizationId: string, requestId: string) => `/organizations/${organizationId}/join-requests/${requestId}/reject`,
  },
  invitations: {
    accept: "/invitations/accept",
  },
  permissions: {
    list: "/permissions",
  },
  roles: {
    list: "/roles",
    permissions: "/roles/permissions",
    create: "/roles",
    details: (roleId: string) => `/roles/${roleId}`,
    update: (roleId: string) => `/roles/${roleId}`,
    delete: (roleId: string) => `/roles/${roleId}`,
  },
  customers: {
    list: "/customers",
    ledger: (customerId: string) => `/customers/${customerId}/ledger`,
    details: (customerId: string) => `/customers/${customerId}`,
  },
  vendors: {
    list: "/vendors",
    ledger: (vendorId: string) => `/vendors/${vendorId}/ledger`,
    details: (vendorId: string) => `/vendors/${vendorId}`,
  },
  products: {
    list: "/products",
    categories: "/products/categories",
    details: (productId: string) => `/products/${productId}`,
    categoryDetails: (categoryId: string) => `/products/categories/${categoryId}`,
  },
  inventory: {
    items: "/inventory/items",
    movements: "/inventory/movements",
    adjustments: "/inventory/adjustments",
    transfers: "/inventory/transfers",
    grn: {
      list: "/inventory/grn",
      details: (id: string) => `/inventory/grn/${id}`,
      create: "/inventory/grn",
      receive: (id: string) => `/inventory/grn/${id}/receive`,
    },
    stockJournals: {
      list: "/inventory/stock-journals",
      details: (id: string) => `/inventory/stock-journals/${id}`,
      create: "/inventory/stock-journals",
      post: (id: string) => `/inventory/stock-journals/${id}/post`,
    },
    batches: "/inventory/batches",
    serials: "/inventory/serials",
    deliveryChallans: "/inventory/delivery-challans",
    stockGroups: {
      list: "/stock-groups",
      details: (id: string) => `/stock-groups/${id}`,
      create: "/stock-groups",
      update: (id: string) => `/stock-groups/${id}`,
      delete: (id: string) => `/stock-groups/${id}`,
    },
  },
  purchases: {
    invoices: "/vendor-invoices",
    invoiceDetails: (id: string) => `/vendor-invoices/${id}`,
    matchSummary: (id: string) => `/vendor-invoices/${id}/match-summary`,
    createInvoice: "/vendor-invoices",
    postInvoice: (id: string) => `/vendor-invoices/${id}/post`,
      payments: {
        list: (id: string) => `/vendor-invoices/${id}/payments`,
        create: (id: string) => `/vendor-invoices/${id}/payments`,
      },
    orders: {
      list: "/purchase-orders",
      details: (id: string) => `/purchase-orders/${id}`,
      create: "/purchase-orders",
      submitApproval: (id: string) => `/purchase-orders/${id}/submit-approval`,
    },
  },
  invoices: {
    list: "/invoices",
    details: (invoiceId: string) => `/invoices/${invoiceId}`,
    pdf: (invoiceId: string) => `/invoices/${invoiceId}/pdf`,
    send: (invoiceId: string) => `/invoices/${invoiceId}/send`,
    emailHistory: (invoiceId: string) => `/invoices/${invoiceId}/email-history`,
  },
  payments: {
    list: "/payments",
    details: (paymentId: string) => `/payments/${paymentId}`,
  },
  transactions: {
    list: "/transactions",
  },
  auditLogs: {
    list: (organizationId: string) => `/organizations/${organizationId}/audit-logs`,
  },
  reports: {
    dashboard: "/reports/dashboard",
    sales: "/reports/sales",
    expenses: "/reports/expenses",
    inventory: "/reports/inventory",
    tax: "/reports/tax",
    export: "/reports/export",
    exportStatus: (jobId: string) => `/reports/export/${jobId}`,
  },
  expenses: {
    list: "/expenses",
    details: (expenseId: string) => `/expenses/${expenseId}`,
  },
  taxes: {
    list: "/taxes",
    details: (taxId: string) => `/taxes/${taxId}`,
  },
  hrms: {
    dashboard: "/employees/dashboard",
    employees: "/employees",
    employeeDetails: (employeeId: string) => `/employees/${employeeId}`,
    attendance: "/attendance",
    leaves: "/leaves",
    leaveDetails: (leaveId: string) => `/leaves/${leaveId}`,
    leaveApproval: (leaveId: string) => `/leaves/${leaveId}/approve`,
    leaveRejection: (leaveId: string) => `/leaves/${leaveId}/reject`,
    payroll: "/payroll",
    shifts: "/shifts",
    holidays: "/holidays",
    claims: "/claims",
    hierarchy: (employeeId: string) => `/employees/${employeeId}/hierarchy`,
    departments: {
      list: "/departments",
      create: "/departments",
      details: (id: string) => `/departments/${id}`,
      update: (id: string) => `/departments/${id}`,
      delete: (id: string) => `/departments/${id}`,
    },
    payrollRuns: {
      list: "/payroll/runs",
      generate: "/payroll/runs/generate",
      details: (id: string) => `/payroll/runs/${id}`,
      submit: (id: string) => `/payroll/runs/${id}/submit`,
    },
    myPayslips: {
      list: "/payroll/my-payslips",
      details: (id: string) => `/payroll/my-payslips/${id}`,
    },
    designations: "/designations",
  },
  approvals: {
    pending: "/approvals/me/pending",
    approve: (id: string) => `/approvals/${id}/approve`,
    reject: (id: string) => `/approvals/${id}/reject`,
  },
  accounting: {
    journals: "/accounting/journals",
    journalDetails: (id: string) => `/accounting/journals/${id}`,
    fiscalYears: "/accounting/fiscal-years",
    accounts: "/accounting/accounts",
    updateAccount: (id: string) => `/accounting/accounts/${id}`,
    reports: {
      trialBalance: "/accounting/reports/trial-balance",
      profitLoss: "/accounting/reports/profit-loss",
      balanceSheet: "/accounting/reports/balance-sheet",
      agingAR: "/accounting/reports/aging/ar",
      agingAP: "/accounting/reports/aging/ap",
    }
  },
} as const;
