export const SYSTEM_ROLE_NAMES = [
  "owner",
  "admin",
  "manager",
  "member",
] as const;

export type SystemRoleName = (typeof SYSTEM_ROLE_NAMES)[number];

export const PERMISSIONS = {
  ORGANIZATION_VIEW: "organization.view",
  ORGANIZATION_UPDATE: "organization.update",
  ORGANIZATION_DELETE: "organization.delete",
  ORGANIZATION_SETTINGS: "organization.settings",
  ORGANIZATION_MEMBERS: "organization.members",
  ORGANIZATION_INVITATIONS: "organization.invitations",
  ORGANIZATION_TRANSFER_OWNERSHIP: "organization.transfer_ownership",
  ROLES_MANAGE: "roles.manage",
  PERMISSIONS_VIEW: "permissions.view",
  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DELETE: "users.delete",
  BILLING_MANAGE: "billing.manage",
  INVENTORY_MANAGE: "inventory.manage",
  WORKSPACE_SWITCH: "workspace.switch",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_UPDATE: "customers.update",
  CUSTOMERS_VIEW: "customers.view",
  VENDORS_CREATE: "vendors.create",
  VENDORS_UPDATE: "vendors.update",
  VENDORS_VIEW: "vendors.view",
  PRODUCTS_MANAGE: "products.manage",
  INVOICES_CREATE: "invoices.create",
  INVOICES_UPDATE: "invoices.update",
  INVOICES_DELETE: "invoices.delete",
  INVOICES_VIEW: "invoices.view",
  PAYMENTS_CREATE: "payments.create",
  PAYMENTS_VIEW: "payments.view",
  EXPENSES_MANAGE: "expenses.manage",
  TAXES_MANAGE: "taxes.manage",
  TRANSACTIONS_VIEW: "transactions.view",
  REPORTS_VIEW: "reports.view",
  AUDIT_LOGS_VIEW: "auditlogs.view",
} as const;

export const DEFAULT_PERMISSIONS = [
  {
    name: PERMISSIONS.ORGANIZATION_VIEW,
    description: "View organization details",
  },
  {
    name: PERMISSIONS.ORGANIZATION_UPDATE,
    description: "Update organization profile and metadata",
  },
  {
    name: PERMISSIONS.ORGANIZATION_DELETE,
    description: "Delete an organization",
  },
  {
    name: PERMISSIONS.ORGANIZATION_SETTINGS,
    description: "Manage organization settings",
  },
  {
    name: PERMISSIONS.ORGANIZATION_MEMBERS,
    description: "Manage organization members",
  },
  {
    name: PERMISSIONS.ORGANIZATION_INVITATIONS,
    description: "Create and manage member invitations",
  },
  {
    name: PERMISSIONS.ORGANIZATION_TRANSFER_OWNERSHIP,
    description: "Transfer organization ownership",
  },
  {
    name: PERMISSIONS.ROLES_MANAGE,
    description: "Manage organization roles",
  },
  {
    name: PERMISSIONS.PERMISSIONS_VIEW,
    description: "View organization permissions",
  },
  {
    name: PERMISSIONS.USERS_VIEW,
    description: "View users in the organization",
  },
  {
    name: PERMISSIONS.USERS_CREATE,
    description: "Create users or invite them into the organization",
  },
  {
    name: PERMISSIONS.USERS_UPDATE,
    description: "Update organization users",
  },
  {
    name: PERMISSIONS.USERS_DELETE,
    description: "Remove users from the organization",
  },
  {
    name: PERMISSIONS.BILLING_MANAGE,
    description: "Manage billing details",
  },
  {
    name: PERMISSIONS.INVENTORY_MANAGE,
    description: "Manage inventory records",
  },
  {
    name: PERMISSIONS.WORKSPACE_SWITCH,
    description: "Switch between workspaces",
  },
  {
    name: PERMISSIONS.CUSTOMERS_CREATE,
    description: "Create customers",
  },
  {
    name: PERMISSIONS.CUSTOMERS_UPDATE,
    description: "Update or archive customers",
  },
  {
    name: PERMISSIONS.CUSTOMERS_VIEW,
    description: "View customers and ledgers",
  },
  {
    name: PERMISSIONS.VENDORS_CREATE,
    description: "Create vendors",
  },
  {
    name: PERMISSIONS.VENDORS_UPDATE,
    description: "Update vendors",
  },
  {
    name: PERMISSIONS.VENDORS_VIEW,
    description: "View vendors and ledgers",
  },
  {
    name: PERMISSIONS.PRODUCTS_MANAGE,
    description: "Manage products and categories",
  },
  {
    name: PERMISSIONS.INVOICES_CREATE,
    description: "Create invoices",
  },
  {
    name: PERMISSIONS.INVOICES_UPDATE,
    description: "Update invoices",
  },
  {
    name: PERMISSIONS.INVOICES_DELETE,
    description: "Cancel or delete invoices",
  },
  {
    name: PERMISSIONS.INVOICES_VIEW,
    description: "View invoices",
  },
  {
    name: PERMISSIONS.PAYMENTS_CREATE,
    description: "Record payments and refunds",
  },
  {
    name: PERMISSIONS.PAYMENTS_VIEW,
    description: "View payments",
  },
  {
    name: PERMISSIONS.EXPENSES_MANAGE,
    description: "Manage expenses",
  },
  {
    name: PERMISSIONS.TAXES_MANAGE,
    description: "Manage taxes",
  },
  {
    name: PERMISSIONS.TRANSACTIONS_VIEW,
    description: "View financial transactions",
  },
  {
    name: PERMISSIONS.REPORTS_VIEW,
    description: "View financial reports",
  },
] as const;

export const SYSTEM_ROLE_PERMISSIONS: Record<SystemRoleName, string[]> = {
  owner: DEFAULT_PERMISSIONS.map((permission) => permission.name),
  admin: [
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_SETTINGS,
    PERMISSIONS.ORGANIZATION_MEMBERS,
    PERMISSIONS.ORGANIZATION_INVITATIONS,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.PERMISSIONS_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.WORKSPACE_SWITCH,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.VENDORS_CREATE,
    PERMISSIONS.VENDORS_UPDATE,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_UPDATE,
    PERMISSIONS.INVOICES_DELETE,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.EXPENSES_MANAGE,
    PERMISSIONS.TAXES_MANAGE,
    PERMISSIONS.TRANSACTIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  manager: [
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_MEMBERS,
    PERMISSIONS.ORGANIZATION_INVITATIONS,
    PERMISSIONS.PERMISSIONS_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.WORKSPACE_SWITCH,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.VENDORS_CREATE,
    PERMISSIONS.VENDORS_UPDATE,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_UPDATE,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.EXPENSES_MANAGE,
    PERMISSIONS.TAXES_MANAGE,
    PERMISSIONS.TRANSACTIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  member: [
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.PERMISSIONS_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.WORKSPACE_SWITCH,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.TRANSACTIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
};
